### ISSUE TITLE
\闯爷/\闯爷/

### ISSUE THREAD

**Issue by bigric3** [bigBestWay/SilverPatcher#2]
tks for your nice work~
i debug code and have some question,,
1.  InstrumentManager.cpp: L338
`		
std::vector<uint8_t> getRIPcode = {
			0xe8, 0,    0,    0,    0, //call 5

			//0x5d, //pop rbp/ebp 获得RIP

			0x58,    // pop rax/eax because inline hook start of main/func, will cover instr eg. mov ebp,esp, so if here pop rbp, 返回main中再使用rbp（比如局部变量寻址等）会sigfault
		};
`

改了这点，后面获取imagebase也稍稍修改(x64为例，x86的分支也改一改)
`
		std::string insn;
		if (!isX32)
		{
            insn = "sub rax, " + std::to_string(cave->virtual_addr + offset + 5);

            insn += ";add rax," + std::to_string(jmpBackAddr);

            insn += ";push rax";

            insn += ";sub rax," + std::to_string(jmpBackAddr);

		    /*
			insn = "sub rbp, " + std::to_string(cave->virtual_addr + offset + 5);

			insn += ";add rbp," + std::to_string(jmpBackAddr);

			insn += ";push rbp";

			insn += ";sub rbp," + std::to_string(jmpBackAddr);

		     */
		}
`

2. BinaryAnalysis.cpp：L162开始做点修改，获取main函数的地址，因为使用uc模拟，代码段地址设置的0x1000000，这里获取的地址为偏移后的，改后（调试的demo是开启pie的）:

`uint64_t mainaddr = 0;
	if (UnicornEngine::instance()->simulate_start(simulate_code, mainaddr) != 0)
	{
		std::cerr << "simulate_start fail.\n";
	}

	uint64_t text_addr;
	mainaddr = mainaddr - ADDRESS;  // ADDRESS为0x1000000
	const Section & text = BinaryEditor::instance()->textSection()；
	text_addr = text.virtual_address();
	mainaddr = mainaddr + text_addr - 0x1000;  // 0x1000为section align

	std::cout << "text_addr va:" << std::hex << text_addr <<std::endl;

	std::cout << "get main " << std::hex << mainaddr << std::endl;
`

3.  无影响，看到了提个suggestion，无影响不必要修改
RandomPLTGOTPolicy.cpp：L81~L82修改如下：
//	BinaryEditor::instance()->getAllRelocations(allrels);
for (auto entry: _binary->relocations())

thank you for your nice code~~~~
\闯爷/\闯爷/

**Comment by bigBestWay** [comment]
感谢关注。第三点，不能修改，修改后编译不过
++++++++++++++++++++++++++++++++++++++
3.无影响，看到了提个suggestion，无影响不必要修改
RandomPLTGOTPolicy.cpp：L81~L82修改如下：
// BinaryEditor::instance()->getAllRelocations(allrels);
for (auto entry: _binary->relocations())

**Comment by bigBestWay** [comment]
第一点，使用RAX而不使用RBP作为计算寄存器，这个肯定是可以的，但现有使用RBP是否能证明有问题。如果没有，我认为修改意义不大。

**Comment by bigBestWay** [comment]
第二点已修复
https://github.com/bigBestWay/SilverPatcher/commit/834e3f9a65a5f3674c6df07534746694c4bce9f0

**Comment by bigBestWay** [comment]
```C
.text:000007A0                                         public start
.text:000007A0                         start           proc near               ; DATA XREF: LOAD:00000018↑o
.text:000007A0 31 ED                                   xor     ebp, ebp
.text:000007A2 5E                                      pop     esi
.text:000007A3 89 E1                                   mov     ecx, esp
.text:000007A5 83 E4 F0                                and     esp, 0FFFFFFF0h
.text:000007A8 50                                      push    eax
.text:000007A9 54                                      push    esp             ; stack_end
.text:000007AA 52                                      push    edx             ; rtld_fini
.text:000007AB E8 22 00 00 00                          call    sub_7D2
.text:000007B0 81 C3 00 18 00 00                       add     ebx, (offset _GLOBAL_OFFSET_TABLE_ - $)
.text:000007B6 8D 83 90 EB FF FF                       lea     eax, (__libc_csu_fini - 1FB0h)[ebx]
.text:000007BC 50                                      push    eax             ; fini
.text:000007BD 8D 83 30 EB FF FF                       lea     eax, (__libc_csu_init - 1FB0h)[ebx]
.text:000007C3 50                                      push    eax             ; init
.text:000007C4 51                                      push    ecx             ; ubp_av
.text:000007C5 56                                      push    esi             ; argc
.text:000007C6 FF B3 40 00 00 00                       push    ds:(main_ptr - 1FB0h)[ebx] ; main
.text:000007CC E8 2F FF FF FF                          call    ___libc_start_main
.text:000007D1 F4                                      hlt
.text:000007D1                         start           endp
```
鉴于存在这种start函数的代码，call    sub_7D2里是mov     ebx, [esp+0]，通过ebx寻址到GOT获取main地址，这种通过unicorn模拟不了。因此恢复以前那种修改start函数的方式，这样rbp/ebp问题也不存在了。
https://github.com/bigBestWay/SilverPatcher/commit/da2ebbf8204f7ab5232e5fa6becabdb357e9cf85
